spring.application.name=cadastro-aluno-backend
spring.datasource.url=jdbc:mysql://localhost:3306/cadastro_aluno
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true